### ISSUE TITLE
Feature Request : Character limit on tags.

### ISSUE THREAD

**Issue by vasef** [sniperwolf/taggingJS#47]
I think we can have a character limit on tags that are being added.

**Comment by earwick** [comment]
+1 for this

you can add it manually on line 420:

`            self.$type_zone = $( document.createElement( "input" ) )
                             .addClass( self.config[ "type-zone-class" ] )
                             .attr( "contenteditable", true )
                             .attr( "maxlength", '#' );
`

still, it would be nice if there was a variable for it! :)

**Comment by eugenio-caicedo** [comment]
That issue can be resolved using the following library:

https://www.jqueryscript.net/form/limit-characters-maxlength.html

````
$(".tagging input").maxLength({ maxChars: 10  });
````
